# meta information
website_title: names_are_hard

theme: names_are_hard
description: >
    Demo website for the names_are_hard theme
baseurl: ""
url: "https://github.com/Chris-Johnston/names_are_hard.git"
github_username: Chris-Johnston
